project_id = "qpozetnbnzdinqkrafze"

[functions.compress-tv-video]
verify_jwt = true

[functions.process-tv-with-gemini]
verify_jwt = true

[functions.process-press-pdf]
verify_jwt = true
import_map = "./functions/process-press-pdf/import_map.json"

[functions.compress-press-pdf]
verify_jwt = false

[functions.process-press-pdf-filesearch]
verify_jwt = true

[functions.search-press-filesearch]
verify_jwt = true

[functions.process-rss-feed]
verify_jwt = false

[functions.process-social-feeds]
verify_jwt = false

[functions.reanalyze-articles]
verify_jwt = false

[functions.process-tv-with-qwen]
verify_jwt = true

[functions.create-user]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.get-typeform-alerts]
verify_jwt = true