
export const defaultCsvData = `NOMBRE,TIPO,NOMBRE CARPETA
101.3,RADIO,101.3
11 Q,RADIO,WQ11
1480 AM,RADIO,AM
80GRADOS.NET,PRENSA,80GRADOS.NET
90 GRADOS,PRENSA,
ABC 15,TV,ABC 15
ACCION 740,RADIO,RADIO
ACCION RADIO 740,RADIO,RADIO
ACTIVOPR.COM,PRENSA,DIGITAL
ALDIATX.COM,PRENSA,ALDIATX.COM
ALFA ROCK 105.7FM,RADIO,RADIO
AMARIEMAGAZINE,PRENSA,
AMBIENTE Y COLOR,PRENSA,AMBIENTE Y COLOR
AMERCIAECONOMICA.COM,PRENSA,AMERICAECONOMICA.COM
AMERICA TEVE,TV,CANAL 24
AMERICA TV,TV,
AOL.COM,PRENSA,AOL.COM
AR.NEWS.YAHOO.COM,PRENSA,AR.NEWS.YAHOO.COM
AUTOGIRO.CRONICAURBANA.COM,PRENSA,
BANDERA.ORG,PRENSA,
BEEVOZ,PRENSA,BEEVOZ
BEHEALTH,PRENSA,
BEVERAGE DYNAMICS,PRENSA,
BEVWHOLESALER.COM,PRENSA,
BIENESTAR,PRENSA,
BLOGRINCON DE LA EDUCACION,PRENSA,BLOGRINCON DE LA EDUCACION
BORICUA 740 AM,RADIO,
BORINQUEN RADIO,RADIO,
BUEN HOGAR,PRENSA,BUEN HOGAR
BUENA VIDA,PRENSA,BUENA VIDA
BUSINESS,PRENSA,BUSINESS
CABLE VISION,TV,CABLE VISION
CADENA NCN,TV,NCN
CANAL 165,TV,DIRECT TV JUSTAS
CANAL 30,TV,30
CANAL 46,TV,TELEVISION
CANAL 58,TV,CANAL 58
CANAL 7,TV,CANAL 7
CARIBBEAN BUSINESS,PRENSA,CARIBBEAN BUSINESS
CARIBBEANBUSINESS.COM,PRENSA,CARIBBEANBUSINESS.COM
CARIBEVISION,TV,CARIBEVISION
CENTRO DE PERIODISMO INVESTIGATIVO (CPI),PRENSA,
CENTROTAMPA.COM,PRENSA,CENTROTAMPA.COM
CIENCIAPR.ORG,PRENSA,CIENCIAPR.ORG
CLARIDAD.COM,PRENSA,CLARIDAD.COM
CNN CANAL 31,TV,TV
CNN EN ESPAÑOL CANAL 48,TV,TV CABLE
CUMBRE 1470 AM,RADIO,CUMBRE 1470 AM
CUMBRE 1470 AM,RADIO,CUMBRE 1470 AM
CYBERNEWS.COM,PRENSA,
DE TODO,PRENSA,DE TODO
DEGUSTANDOLAVIDA.COM,PRENSA,
DIALOGODIGITAL.COM,PRENSA,DIALOGODIGITAL.COM
DIALOGOUPR.COM,PRENSA,DIALOGOUPR.COM
DIARIO DE PUERTO RICO.COM,PRENSA,DIARIO DE PUERTO RICO.COM
DIARIOMAS.HN,PRENSA,INTERNET
DIMELO DE FRENTE,RADIO,DIMELO DE FRENTE
DIRECTV ZONE,PRENSA,DIRECTV ZONE
EFE,PRENSA,
EL ADOQUIN,PRENSA,
EL EXPRESSO,PRENSA,EL EXPRESSO
EL JAMON DEL SANDWICH,RADIO,LA MEGA
EL NORTE,PRENSA,EL NORTE
EL NUEVO DIA,PRENSA,EL NUEVO DIA
EL NUEVO HERALD.COM,PRENSA,EL NUEVO HERALD.COM
EL NUEVO PERIODICO,PRENSA,EL NUEVO PERIODICO
EL ORIENTAL,PRENSA,EL ORIENTAL
EL PATRIOTA DEL SUR,PRENSA,
EL PERIODICO,PRENSA,EL PERIODICO
EL PERIODICO NUEVO,PRENSA,EL PERIODICO NUEVO
EL REGIONAL DE GUAYAMA,PRENSA,EL REGIONAL DE GUAYAMA
EL SOL DE PUERTO RICO,PRENSA,
EL TODO,PRENSA,EL TODO
EL VOCERO,PRENSA,EL VOCERO
ELCALCE.COM,PRENSA,
ELECONOMISTA.ES,PRENSA,
ELESPECTADOR.COM,PRENSA,
ELEXPRESSO.COM,PRENSA,
ELFORODEPUERTORICO.COM,PRENSA,
ELHERALDO.COM,PRENSA,ELHERALDO.COM
ELMUNDO.PR,PRENSA,ELMUNDO.PR
ELNUEVODIARIO.COM,PRENSA,ELNUEVODIARIO.COM
ELORIENTALPR.NET,PRENSA,ELORIENTALPR.NET
ELPOSTANTILLANO.NET,PRENSA,ELPOSTANTILLANO.NET
ELREGIONALDIGITAL.COM,PRENSA,ELREGIONALDIGITAL.COM
ELSURALAVISTA.COM,PRENSA,ELSURALAVISTA.COM
ELUNIVERSAL.COM,PRENSA,INTERNET
ELVIGIAPR.COM,PRENSA,
EN VIVO PR.COM,PRENSA,EN VIVO PR.COM
ENDI.COM,PRENSA,ENDI.COM
ENTORNOINTELIGENTE.COM,PRENSA,ENTORNOINTELIGENTE.COM
ENVIVOPR.COM,PRENSA,ENVIVOPR.COM
ES MENTAL,PRENSA,
ESNOTICIAPR,PRENSA,
ESTEREOTEMPO,RADIO,
ETAIWANNEWS.COM,PRENSA,ETAIWANNEWS.COM
EXPANSION.COM,PRENSA,EXPANSION.COM
EXPRESION,PRENSA,EXPRESION
EXPRESION,PRENSA,EXPRESION
EYBORICUA.COM,PRENSA,
FACEBOOK,RADIO,FACEBOOK
FIDELITY 95.7,RADIO,
FOOD BUSINESS,PRENSA,
FOODIES PR,PRENSA,
FORONOTICIOSO.COM,PRENSA,
FOTO GEMA LA REVISTA,PRENSA,FOTO GEMA LA REVISTA
FUTBOLBORICUA.NET,PRENSA,FUTBOLBORICUA.NET
GASTROBAR,PRENSA,
HASHTAG,RADIO,RADIO
HECHOENCALIFORNIA1010.COM,PRENSA,
HECHOS.COM.DO,PRENSA,
HISPANICPR WIRE,PRENSA,
HOLACIUDAD.COM,PRENSA,HOLACIUDAD.COM
HOLANEWS.COM,PRENSA,
HORIZONTE,PRENSA,HORIZONTE
IEEFA.ORG,PRENSA,
IMAGEN,PRENSA,IMAGEN
IN PUERTO RICO,PRENSA,
INDICE,PRENSA,INDICE
INDICE EL NORTE,PRENSA,INDICE NORTE
INDICE SUR OESTE,PRENSA,INDICE SUR OESTE
INDICEPR.COM,PRENSA,INDICEPR.COM
INFORMANDOPR.COM,PRENSA,INFORMANDOPR
INFORMATE PUERTO RICO,PRENSA,
JANGUEANDO EN EL WEEKEND,PRENSA,
JAYFONSECA.COM,PRENSA,
LA CORDILLERA,PRENSA,LA CORDILLERA
LA ESQUINA,PRENSA,LA ESQUINA
LA ESTRELLA,PRENSA,PERIODICO REGIONAL
LA ESTRELLA NORTE,PRENSA,LA ESTRELLA NORTE
LA ESTRELLA OESTE,PRENSA,LA ESTRELLA OESTE
LA MEGA,RADIO,LA MEGA
LA NUEVA 94,RADIO,LA NUEVA 94
LA NUEVA OPINION DEL SUR,PRENSA,LA NUEVA OPINION DEL SUR
LA OPINION DEL SUR,PRENSA,LA OPINION DEL SUR
LA PERLA DEL SUR,PRENSA,LA PERLA DEL SUR
LA REGATA,PRENSA,PERIODICO REGIONAL
LA ROCA,RADIO,AM
LA SEMANA,PRENSA,LA SEMANA
LA X 100.7,RADIO,
LAALDEA.CL,PRENSA,LAALDEA.CL
LACALLEREVISTA.COM,PRENSA,LACALLEREVISTA.COM
LAISLAOESTE.COM,PRENSA,
LAPERLADELSUR.COM,PRENSA,LAPERLADELSUR.COM
LAPICEROVERDE.COM,PRENSA,LAPICEROVERDE.COM
LAVOZDIGITALPR.COM,PRENSA,
LIVE & LIVE IN PALMAS,PRENSA,LIVE & LIVE IN PALMAS
LOGISTICA COMERCIO INTERNACIONAL,PRENSA,
LOSBRUJOSDEGUAYAMA.COM,PRENSA,
MAGACIN.COM,PRENSA,MAGACIN.COM
MAGAZINE PR,PRENSA,MAGAZINE-PR.COM
MAGIC 97.3,RADIO,MAGIC 97.3
MAREAECOLOGISTA.COM,PRENSA,
MAXIMA 940 AM,RADIO,RADIO
MEGA TV,TV,CANAL 60
METRO,PRENSA,METRO
METRO SALUD,PRENSA,
METRO.PR,PRENSA,METRO.PR
MICROJURIS.COM,PRENSA,MICROJURIS.COM
MIPRV.COM,PRENSA,MIPRV.COM
MITV,PRENSA,MITV
MIX 107.7 FM,RADIO,RADIO
NEWENERGYEVENTS.COM,PRENSA,
NEWSISMYBUSINESS.COM,PRENSA,INTERNET
NOTI UNO RADIO 630 AM,RADIO,
NOTICEL.COM,PRENSA,NOTICEL.COM
NOTICIAS 24\\7,PRENSA,NOTICIAS 24\\7
NOTICIASDEPONCE.NET,PRENSA,
NOTICIASXTRA.COM,PRENSA,
NOTILUZ,RADIO,
NOTISEIS 360 DIGITAL,TV,
NOTIUNO.COM,PRENSA,NOTIUNO.COM
NPR,PRENSA,
NUEVA VIDA,RADIO,
NUEVA VISION,TV,
OCEAN DRIVE,PRENSA,OCEAN DRIVE
PAPARAZZI,PRENSA,PAPARAZZI
PEOPLEENESPAÑOL.COM,PRENSA,DIGITAL
PEOPLEENESPANOL.COM,PRENSA,
PERIODICO IMPACTO NORESTE,PRENSA,PERIODICO IMPACTO NORESTE
PERIODICO VISION,PRENSA,PERIODICO VISION
PERIODICOLAPERLA.COM,PRENSA,PERIODICOLAPERLA.COM
PERIODISMOINVESTIGATIVO.COM,PRENSA,PERIODISMOINVESTIGATIVO.COM
PIAOFPR.COM,PRENSA,PIAOFPR.COM
PICCOLOMONDOPR BLOG,PRENSA,PICCOLOMONDOPR BLOG
PLACERES PR,PRENSA,
PLATEA PR,PRENSA,
PLAY 96.5 FM,RADIO,PLAY 96.5 FM
PR HEADLINE NEWS,PRENSA,
PR INSIDE.COM,PRENSA,PR INSIDE.COM
PR NEWSWIRE,PRENSA,
PR SPORT,PRENSA,PR SPORT
PRDAILYSUN.COM,PRENSA,PRDAILYSUN.COM
PRENSA SIN CENSURA,PRENSA,
PRESENCIA,PRENSA,PRESENCIA
PRESENCIAPR.COM,PRENSA,PRESENCIAPR.COM
PRIMERA HORA,PRENSA,PRIMERA HORA
PRIMERA HORA.COM,PRENSA,PRIMERA HORA.COM
PRISMADIGITAL.ORG,PRENSA,PRISMADIGITAL.ORG
PRTV,TV,PRTV
PUERTO RICO DAILY SUN,PRENSA,PUERTO RICO DAILY SUN
PUERTORICO.COM.PR,PRENSA,
PUERTORICOPOSTS.COM,PRENSA,
PUERTORICOTEQUIERO.COM,PRENSA,INTERNET
QUEHAGOCONLOSNENES.COM,PRENSA,INTERNET
QUEPALO.COM,PRENSA,QUEPALO.COM
RADIO 740 AM,RADIO,RADIO AM
RADIO ATENAS 1500 AM,RADIO,RADIO ATENAS 1500 AM
RADIO ISLA 1320 AM,RADIO,
RADIO JOE,RADIO,RADIO JOE
RADIO ORO,RADIO,RADIO
RADIO PAZ 810AM,RADIO,RADIO AM
RADIO REDENTOR 104.1,RADIO,
RADIO UNIVERSIDAD,RADIO,RADIO UNIVERSIDAD
RADIO VIDA,RADIO,RADIO FM
RADIO VIEQUES,RADIO,RADIO
RADIO WALO,RADIO,RADIO AM
RADIO WOSO,RADIO,RADIO WOSO
RADIO YUNQUE 92.5 FM,RADIO,RADIO YUNQUE 92.5 FM
RADIOISLA1320.COM,PRENSA,RADIOISLA1320.COM
RED 96 FM,RADIO,RED 96 FM
REDBIOBIO.COM,PRENSA,REDBIOBIO.COM
REGGAETON 94.7,RADIO,REGGAETON 94.7
RESUMEN LATINOAMERICANO,PRENSA,
REVISTA CROSSOVER,PRENSA,
REVISTA EN SALUD,PRENSA,
REVISTA EN SALUD,PRENSA,REVISTA EN SALUD
REVISTA MIRAME SIEMPRE,PRENSA,
RIVALTIMES.COM,PRENSA,
RMASOCIADOSPR.COM,PRENSA,RMASOCIADOSPR.COM
ROBB REPORT,PRENSA,
RONDA,PRENSA,
RUMBOALCAMERINO.COM,PRENSA,INTERNET
RUMRAIDERS.COM,PRENSA,
SABROSIA PUERTO RICO,PRENSA,
SALD 1520 AM,RADIO,AM
SALSOUL 98.5,RADIO,
SAN JUAN NEWS,PRENSA,SAN JUAN NEWS
SAN JUAN WEEKLY STAR,PRENSA,SAN JUAN WEEKLY STAR
SANTILLANA.COM,PRENSA,SANTILLANA.COM
SENADO EN CONTACTO,PRENSA,SENADO EN CONTACTO
SENADO EN CONTACTO,PRENSA,SENADO EN CONTACTO
SINCENSURA.COM,PRENSA,
SINCOMILLAS.COM,PRENSA,SINCOMILLAS.COM
SISTEMA 102.5,RADIO,
SITV CANAL 40,TV,TELEVISION
SOLAR NOVUS,PRENSA,
SOLBORINCANO.COM,PRENSA,
STUDOCU.COM,PRENSA,
SUPER K 106.5 FM,RADIO,SUPER K 106.5 FM
TELE ORO,TV,TELE ORO
TELEMUNDO,TV,02
TELEMUNDOPR.COM,PRENSA,TELEMUNDOPR.COM
TELEONCE,TV,
TELEVICENTRO,TV,04
THE SAN JUAN DAILY STAR,PRENSA,THE SAN JUAN DAILY STAR
THE SAN JUAN STAR INGLES,PRENSA,THE SAN JUAN STAR INGLES
THE SPIRITS BUSINESS,PRENSA,
THE WEEKLY JOURNAL,PRENSA,
THEDRINKSBUSINESS.COM,PRENSA,
THEDRINKSREPORT.COM,PRENSA,
THERUMLAB.COM,PRENSA,
TIVA TV,TV,TIVA TV
TOCA DE TO,RADIO,RADIO
TODAY NEW POST,PRENSA,
TRENDHUNTER.COM,PRENSA,
TU CAMARA INFORMA,PRENSA,TU CAMARA INFORMA
TU TV,TV,06
TUNOTICIAPR.COM,PRENSA,
TV AQUI,PRENSA,TV AQUI
TV Y NOVELAS,PRENSA,TV Y NOVELAS
UNICA 1230 AM,RADIO,RADIO
UNIVERSIA.PR,PRENSA,UNIVERSIA.PR
UNIVERSIA.TV,PRENSA,UNIVERSIA.TV
UNIVISION,TV,11
UNIVISION.COM,PRENSA,UNIVISION.COM
USDA.GOV,PRENSA,
VANGUARDIA.COM,PRENSA,VANGUARDIA.COM
VANIDADES,PRENSA,VANIDADES
VEA,PRENSA,VEA
VIBEERMAG.COM,PRENSA,
VICE.COM,PRENSA,
VILLALBAONLINEPR.COM,PRENSA,DIGITAL
VISION,PRENSA,VISION
VISION NORTE,PRENSA,VISION NORTE
VISION OESTE,PRENSA,VISION OESTE
VOCERO.COM,PRENSA,VOCERO.COM
VOCESDELSURPR.COM,,
VOCESDELSURPR.COM,PRENSA,
WALO,PRENSA,
WALO 1240,RADIO,RADIO AM
WAPA,TV,WAPA CANAL 4
WAPA RADIO 680 AM,RADIO,
WAPA.TV.COM,PRENSA,WAPA.TV.COM
WHOY,RADIO,WHOY 1210
WIAC,RADIO,RADIO
WIBS,RADIO,WIBS 1540
WIPR,RADIO,WIPR
WIPR,TV,
WIPR.PR,PRENSA,
WKAQ RADIO 580 AM,RADIO,
WKVM,RADIO,WKVM
WKVM-810AM,RADIO,RADIO AM
WORA,PRENSA,
WPAB,RADIO,RADIO
WQBS,RADIO,WQBS
WRADIO.COM,PRENSA,WRADIO.COM
WTIL 1300,RADIO,RADIO
X61,RADIO,X61 610
YOURTRIPAGENT.COM,PRENSA,
Z-93,RADIO,`;
